import type { SearchSuggestion } from "./types";

/**
 * Extended suggestion pool for the guess autocomplete. These tracks appear in
 * the suggestion dropdown but are NOT in the playable catalog — they exist only
 * to give the player a familiar list to scroll through when they half-know a
 * title. The list covers major chart hits across every era and genre so common
 * guesses always surface a matching option even for songs Cluetune doesn't
 * host audio for.
 *
 * Keep entries deduplicated against CATALOG where possible; duplicates are
 * harmless (the search layer dedupes by artist+title) but waste space.
 */

function s(title: string, artist: string, year: number): SearchSuggestion {
  return { id: `extra:${artist.toLowerCase().replace(/\s+/g, "-")}:${title.toLowerCase().replace(/\s+/g, "-")}`, title, artist, year };
}

export const EXTRA_SUGGESTIONS: SearchSuggestion[] = [
  // ── Pop / Mainstream ─────────────────────────────────────────────────────
  s("Shape of You", "Ed Sheeran", 2017),
  s("Perfect", "Ed Sheeran", 2017),
  s("Thinking Out Loud", "Ed Sheeran", 2014),
  s("Bad Habits", "Ed Sheeran", 2021),
  s("Photograph", "Ed Sheeran", 2014),
  s("Castle on the Hill", "Ed Sheeran", 2017),
  s("Shivers", "Ed Sheeran", 2021),
  s("Someone Like You", "Adele", 2011),
  s("Hello", "Adele", 2015),
  s("Easy On Me", "Adele", 2021),
  s("Set Fire to the Rain", "Adele", 2011),
  s("Skyfall", "Adele", 2012),
  s("Water Under the Bridge", "Adele", 2015),
  s("Million Reasons", "Lady Gaga", 2016),
  s("Just Dance", "Lady Gaga", 2008),
  s("Poker Face", "Lady Gaga", 2008),
  s("Telephone", "Lady Gaga", 2009),
  s("Bad Romance", "Lady Gaga", 2009),
  s("Born This Way", "Lady Gaga", 2011),
  s("Shallow", "Lady Gaga", 2018),
  s("Hold My Hand", "Lady Gaga", 2022),
  s("Applause", "Lady Gaga", 2013),
  s("Umbrella", "Rihanna", 2007),
  s("Diamonds", "Rihanna", 2012),
  s("Stay", "Rihanna", 2012),
  s("Only Girl (In the World)", "Rihanna", 2010),
  s("S&M", "Rihanna", 2010),
  s("Disturbia", "Rihanna", 2008),
  s("Needed Me", "Rihanna", 2016),
  s("Work", "Rihanna", 2016),
  s("Anti-Hero", "Taylor Swift", 2022),
  s("Shake It Off", "Taylor Swift", 2014),
  s("Love Story", "Taylor Swift", 2008),
  s("You Belong with Me", "Taylor Swift", 2008),
  s("Style", "Taylor Swift", 2014),
  s("Blank Space", "Taylor Swift", 2014),
  s("Bad Blood", "Taylor Swift", 2014),
  s("Wildest Dreams", "Taylor Swift", 2015),
  s("Look What You Made Me Do", "Taylor Swift", 2017),
  s("Delicate", "Taylor Swift", 2017),
  s("cardigan", "Taylor Swift", 2020),
  s("august", "Taylor Swift", 2020),
  s("All Too Well (10 Minute Version)", "Taylor Swift", 2021),
  s("Karma", "Taylor Swift", 2022),
  s("Lavender Haze", "Taylor Swift", 2022),
  s("Midnight Rain", "Taylor Swift", 2022),
  s("Shake It Off", "Taylor Swift", 2014),
  s("Can't Stop the Feeling!", "Justin Timberlake", 2016),
  s("Mirrors", "Justin Timberlake", 2013),
  s("SexyBack", "Justin Timberlake", 2006),
  s("What Goes Around... Comes Around", "Justin Timberlake", 2006),
  s("Cry Me a River", "Justin Timberlake", 2002),
  s("Suit & Tie", "Justin Timberlake", 2013),
  s("Rock Your Body", "Justin Timberlake", 2002),
  s("Señorita", "Shawn Mendes", 2019),
  s("Stitches", "Shawn Mendes", 2015),
  s("Mercy", "Shawn Mendes", 2016),
  s("In My Blood", "Shawn Mendes", 2018),
  s("There's Nothing Holdin' Me Back", "Shawn Mendes", 2017),
  s("Wonder", "Shawn Mendes", 2020),
  s("Watermelon Sugar", "Harry Styles", 2019),
  s("Adore You", "Harry Styles", 2019),
  s("Golden", "Harry Styles", 2019),
  s("Sign of the Times", "Harry Styles", 2017),
  s("Lights Up", "Harry Styles", 2019),
  s("Treat People with Kindness", "Harry Styles", 2020),
  s("Music for a Sushi Restaurant", "Harry Styles", 2022),
  s("Late Night Talking", "Harry Styles", 2022),
  s("Levitating", "Dua Lipa", 2020),
  s("Don't Start Now", "Dua Lipa", 2019),
  s("Physical", "Dua Lipa", 2020),
  s("Break My Heart", "Dua Lipa", 2020),
  s("New Rules", "Dua Lipa", 2017),
  s("One Kiss", "Dua Lipa", 2018),
  s("IDGAF", "Dua Lipa", 2017),
  s("Cold Heart", "Dua Lipa", 2021),
  s("Houdini", "Dua Lipa", 2023),
  s("Training Season", "Dua Lipa", 2024),
  s("Illusion", "Dua Lipa", 2024),
  s("Please Please Please", "Sabrina Carpenter", 2024),
  s("Nonsense", "Sabrina Carpenter", 2022),
  s("Feather", "Sabrina Carpenter", 2023),
  s("emails i can't send", "Sabrina Carpenter", 2022),
  s("Taste", "Sabrina Carpenter", 2024),
  s("Busy Woman", "Sabrina Carpenter", 2025),
  s("Bad Guy", "Billie Eilish", 2019),
  s("Happier Than Ever", "Billie Eilish", 2021),
  s("Ocean Eyes", "Billie Eilish", 2016),
  s("bury a friend", "Billie Eilish", 2019),
  s("Therefore I Am", "Billie Eilish", 2020),
  s("Lovely", "Billie Eilish", 2018),
  s("when the party's over", "Billie Eilish", 2018),
  s("What Was I Made For?", "Billie Eilish", 2023),
  s("BIRDS OF A FEATHER", "Billie Eilish", 2024),
  s("lunch", "Billie Eilish", 2024),
  s("Blinding Lights", "The Weeknd", 2019),
  s("Starboy", "The Weeknd", 2016),
  s("Can't Feel My Face", "The Weeknd", 2015),
  s("The Hills", "The Weeknd", 2015),
  s("Save Your Tears", "The Weeknd", 2020),
  s("Earned It", "The Weeknd", 2015),
  s("I Feel It Coming", "The Weeknd", 2016),
  s("Call Out My Name", "The Weeknd", 2018),
  s("Die for You", "The Weeknd", 2016),
  s("Take My Breath", "The Weeknd", 2021),
  s("Creepin'", "Metro Boomin", 2022),
  s("Popular", "The Weeknd", 2023),
  s("Timeless", "The Weeknd", 2024),
  s("São Paulo", "The Weeknd", 2024),
  s("Happier", "Marshmello", 2018),
  s("Wolves", "Marshmello", 2017),
  s("Sunflower", "Post Malone", 2018),
  s("Circles", "Post Malone", 2019),
  s("Rockstar", "Post Malone", 2017),
  s("Better Now", "Post Malone", 2018),
  s("Congratulations", "Post Malone", 2016),
  s("White Iverson", "Post Malone", 2015),
  s("Go Flex", "Post Malone", 2016),
  s("Leave the Door Open", "Silk Sonic", 2021),
  s("Smokin Out the Window", "Silk Sonic", 2021),
  s("After Last Night", "Silk Sonic", 2021),
  s("Fly As Me", "Silk Sonic", 2021),
  s("Positions", "Ariana Grande", 2020),
  s("7 rings", "Ariana Grande", 2019),
  s("thank u, next", "Ariana Grande", 2018),
  s("Problem", "Ariana Grande", 2014),
  s("No Tears Left to Cry", "Ariana Grande", 2018),
  s("Into You", "Ariana Grande", 2016),
  s("Side to Side", "Ariana Grande", 2016),
  s("break up with your girlfriend, i'm bored", "Ariana Grande", 2019),
  s("God is a woman", "Ariana Grande", 2018),
  s("Dangerous Woman", "Ariana Grande", 2016),
  s("yes, and?", "Ariana Grande", 2024),
  s("we can't be friends", "Ariana Grande", 2024),

  // ── R&B / Soul ────────────────────────────────────────────────────────────
  s("No Scrubs", "TLC", 1999),
  s("Waterfalls", "TLC", 1994),
  s("Creep", "TLC", 1992),
  s("Say My Name", "Destiny's Child", 1999),
  s("Survivor", "Destiny's Child", 2001),
  s("Bootylicious", "Destiny's Child", 2001),
  s("Bills, Bills, Bills", "Destiny's Child", 1999),
  s("Crazy in Love", "Beyoncé", 2003),
  s("Halo", "Beyoncé", 2008),
  s("Single Ladies (Put a Ring on It)", "Beyoncé", 2008),
  s("Irreplaceable", "Beyoncé", 2006),
  s("Love On Top", "Beyoncé", 2011),
  s("XO", "Beyoncé", 2013),
  s("Drunk in Love", "Beyoncé", 2013),
  s("Lemonade", "Beyoncé", 2016),
  s("Formation", "Beyoncé", 2016),
  s("Hold Up", "Beyoncé", 2016),
  s("CUFF IT", "Beyoncé", 2022),
  s("BREAK MY SOUL", "Beyoncé", 2022),
  s("TEXAS HOLD 'EM", "Beyoncé", 2024),
  s("16 CARRIAGES", "Beyoncé", 2024),
  s("All of Me", "John Legend", 2013),
  s("Ordinary People", "John Legend", 2004),
  s("Get Lifted", "John Legend", 2004),
  s("Preach", "John Legend", 2019),
  s("Stay with You", "John Legend", 2005),
  s("Slow Dance", "John Legend", 2018),
  s("Use Somebody", "Kings of Leon", 2008),
  s("Sex on Fire", "Kings of Leon", 2008),
  s("Notion", "Kings of Leon", 2008),

  // ── Hip-Hop / Rap ─────────────────────────────────────────────────────────
  s("HUMBLE.", "Kendrick Lamar", 2017),
  s("Swimming Pools (Drank)", "Kendrick Lamar", 2012),
  s("Money Trees", "Kendrick Lamar", 2012),
  s("Poetic Justice", "Kendrick Lamar", 2012),
  s("King Kunta", "Kendrick Lamar", 2015),
  s("Alright", "Kendrick Lamar", 2015),
  s("DNA.", "Kendrick Lamar", 2017),
  s("LOYALTY.", "Kendrick Lamar", 2017),
  s("Not Like Us", "Kendrick Lamar", 2024),
  s("meet the grahams", "Kendrick Lamar", 2024),
  s("euphoria", "Kendrick Lamar", 2024),
  s("God's Plan", "Drake", 2018),
  s("Hotline Bling", "Drake", 2015),
  s("One Dance", "Drake", 2016),
  s("Started from the Bottom", "Drake", 2013),
  s("Hold On, We're Going Home", "Drake", 2013),
  s("Passionfruit", "Drake", 2017),
  s("In My Feelings", "Drake", 2018),
  s("Nice for What", "Drake", 2018),
  s("Toosie Slide", "Drake", 2020),
  s("Rich Flex", "Drake", 2022),
  s("Search & Rescue", "Drake", 2023),
  s("SICKO MODE", "Travis Scott", 2018),
  s("goosebumps", "Travis Scott", 2016),
  s("Antidote", "Travis Scott", 2015),
  s("Butterfly Effect", "Travis Scott", 2017),
  s("Highest in the Room", "Travis Scott", 2019),
  s("FRANCHISE", "Travis Scott", 2020),
  s("STARGAZING", "Travis Scott", 2018),
  s("FE!N", "Travis Scott", 2023),
  s("Thank Me Later", "Drake", 2010),
  s("Bodak Yellow", "Cardi B", 2017),
  s("I Like It", "Cardi B", 2018),
  s("WAP", "Cardi B", 2020),
  s("Up", "Cardi B", 2021),
  s("MAMIII", "Becky G", 2022),
  s("Old Town Road", "Lil Nas X", 2018),
  s("INDUSTRY BABY", "Lil Nas X", 2021),
  s("MONTERO (Call Me by Your Name)", "Lil Nas X", 2021),
  s("THATS WHAT I WANT", "Lil Nas X", 2021),
  s("Sicko Mode", "Travis Scott", 2018),
  s("Mask Off", "Future", 2017),
  s("March Madness", "Future", 2016),
  s("Life Is Good", "Future", 2020),
  s("Keeping it 100", "Future", 2020),
  s("Way 2 Sexy", "Drake", 2021),
  s("Forever", "Drake", 2009),
  s("Take Care", "Drake", 2011),
  s("Headlines", "Drake", 2011),
  s("Marvin's Room", "Drake", 2011),
  s("Blessings", "Drake", 2015),
  s("Shot for Me", "Drake", 2011),
  s("Energy", "Drake", 2015),
  s("Controlla", "Drake", 2016),
  s("Too Good", "Drake", 2016),
  s("Fake Love", "Drake", 2016),
  s("Gyalchester", "Drake", 2017),
  s("Nonstop", "Drake", 2018),
  s("Jaded", "Drake", 2018),
  s("Mob Ties", "Drake", 2018),
  s("Money in the Grave", "Drake", 2019),
  s("When to Say When", "Drake", 2020),
  s("Laugh Now Cry Later", "Drake", 2020),
  s("Greece", "Drake", 2020),
  s("What's Next", "Drake", 2021),
  s("Fair Trade", "Drake", 2021),
  s("Champagne Poetry", "Drake", 2021),
  s("Knife Talk", "Drake", 2021),
  s("N 2 Deep", "Drake", 2021),
  s("TSU", "Drake", 2022),
  s("Texts Go Green", "Drake", 2022),
  s("Massive", "Drake", 2022),
  s("Sticky", "Drake", 2022),
  s("Yebba's Heartbreak", "Drake", 2022),
  s("Broke Boys", "Drake", 2023),
  s("Slime You Out", "Drake", 2023),
  s("You Broke My Heart", "Drake", 2023),
  s("SICKO MODE", "Travis Scott", 2018),
  s("Out West", "JACKBOYS", 2019),
  s("Can't Say", "Travis Scott", 2018),
  s("WAKE UP", "Travis Scott", 2019),
  s("Escape Plan", "Travis Scott", 2021),
  s("Mafia", "Travis Scott", 2021),
  s("LOST FOREVER", "Travis Scott", 2023),
  s("K-POP", "Travis Scott", 2023),
  s("MY EYES", "Travis Scott", 2023),
  s("TIL FURTHER NOTICE", "Travis Scott", 2021),

  // ── Rock / Alternative ────────────────────────────────────────────────────
  s("Smells Like Teen Spirit", "Nirvana", 1991),
  s("Come as You Are", "Nirvana", 1991),
  s("Lithium", "Nirvana", 1991),
  s("In Bloom", "Nirvana", 1991),
  s("Heart-Shaped Box", "Nirvana", 1993),
  s("All Apologies", "Nirvana", 1993),
  s("Rape Me", "Nirvana", 1993),
  s("About a Girl", "Nirvana", 1989),
  s("Bohemian Rhapsody", "Queen", 1975),
  s("We Will Rock You", "Queen", 1977),
  s("Don't Stop Me Now", "Queen", 1978),
  s("Under Pressure", "Queen", 1981),
  s("Somebody to Love", "Queen", 1976),
  s("Radio Ga Ga", "Queen", 1984),
  s("I Want to Break Free", "Queen", 1984),
  s("We Are the Champions", "Queen", 1977),
  s("Killer Queen", "Queen", 1974),
  s("Another One Bites the Dust", "Queen", 1980),
  s("Bicycle Race", "Queen", 1978),
  s("Sweet Child O' Mine", "Guns N' Roses", 1987),
  s("Welcome to the Jungle", "Guns N' Roses", 1987),
  s("November Rain", "Guns N' Roses", 1991),
  s("Paradise City", "Guns N' Roses", 1987),
  s("Patience", "Guns N' Roses", 1988),
  s("Back in Black", "AC/DC", 1980),
  s("Highway to Hell", "AC/DC", 1979),
  s("Thunderstruck", "AC/DC", 1990),
  s("You Shook Me All Night Long", "AC/DC", 1980),
  s("Whole Lotta Rosie", "AC/DC", 1977),
  s("Stairway to Heaven", "Led Zeppelin", 1971),
  s("Whole Lotta Love", "Led Zeppelin", 1969),
  s("Black Dog", "Led Zeppelin", 1971),
  s("Kashmir", "Led Zeppelin", 1975),
  s("Rock and Roll", "Led Zeppelin", 1971),
  s("Hotel California", "Eagles", 1976),
  s("Desperado", "Eagles", 1973),
  s("Life in the Fast Lane", "Eagles", 1977),
  s("Take It Easy", "Eagles", 1972),
  s("Don't Fear the Reaper", "Blue Öyster Cult", 1976),
  s("Eye of the Tiger", "Survivor", 1982),
  s("Don't Stop Believin'", "Journey", 1981),
  s("Any Way You Want It", "Journey", 1980),
  s("Open Arms", "Journey", 1981),
  s("Mr. Brightside", "The Killers", 2003),
  s("Somebody Told Me", "The Killers", 2004),
  s("All These Things That I've Done", "The Killers", 2004),
  s("Human", "The Killers", 2008),
  s("Spaceman", "The Killers", 2008),
  s("Smile Like You Mean It", "The Killers", 2004),
  s("Everything in Its Right Place", "Radiohead", 2000),
  s("Karma Police", "Radiohead", 1997),
  s("Creep", "Radiohead", 1992),
  s("Fake Plastic Trees", "Radiohead", 1995),
  s("High and Dry", "Radiohead", 1995),
  s("Street Spirit (Fade Out)", "Radiohead", 1995),
  s("Yellow", "Coldplay", 2000),
  s("The Scientist", "Coldplay", 2002),
  s("Fix You", "Coldplay", 2005),
  s("Speed of Sound", "Coldplay", 2005),
  s("Clocks", "Coldplay", 2002),
  s("In My Place", "Coldplay", 2002),
  s("Viva la Vida", "Coldplay", 2008),
  s("The Hardest Part", "Coldplay", 2006),
  s("A Sky Full of Stars", "Coldplay", 2014),
  s("Adventure of a Lifetime", "Coldplay", 2015),
  s("My Universe", "Coldplay", 2021),
  s("Higher Power", "Coldplay", 2021),
  s("We Pray", "Coldplay", 2024),
  s("feelslikeimfallinginlove", "Coldplay", 2024),
  s("Seven Nation Army", "The White Stripes", 2003),
  s("Icky Thump", "The White Stripes", 2007),
  s("Fell in Love with a Girl", "The White Stripes", 2002),
  s("Hotel Yorba", "The White Stripes", 2001),
  s("Elephant", "The White Stripes", 2003),
  s("I Will Follow You into the Dark", "Death Cab for Cutie", 2005),
  s("Soul Meets Body", "Death Cab for Cutie", 2005),
  s("Someday You Will Be Loved", "Death Cab for Cutie", 2005),
  s("I Miss You", "blink-182", 2003),
  s("What's My Age Again?", "blink-182", 1999),
  s("All the Small Things", "blink-182", 1999),
  s("Adam's Song", "blink-182", 1999),
  s("Dammit", "blink-182", 1997),
  s("The Rock Show", "blink-182", 2001),
  s("Chasing Cars", "Snow Patrol", 2006),
  s("Chocolate", "Snow Patrol", 2003),
  s("Run", "Snow Patrol", 2003),
  s("Open Your Eyes", "Snow Patrol", 2006),
  s("Boulevard of Broken Dreams", "Green Day", 2004),
  s("American Idiot", "Green Day", 2004),
  s("Wake Me Up When September Ends", "Green Day", 2004),
  s("Good Riddance (Time of Your Life)", "Green Day", 1997),
  s("Basket Case", "Green Day", 1994),
  s("Holiday", "Green Day", 2004),
  s("When I Come Around", "Green Day", 1994),
  s("Warning", "Green Day", 2000),
  s("21 Guns", "Green Day", 2009),
  s("Know Your Enemy", "Green Day", 2009),

  // ── Indie / Alternative ───────────────────────────────────────────────────
  s("Ribs", "Lorde", 2013),
  s("Tennis Court", "Lorde", 2013),
  s("Team", "Lorde", 2013),
  s("Pure Heroine", "Lorde", 2013),
  s("Hard Feelings/Loveless", "Lorde", 2017),
  s("Liability", "Lorde", 2017),
  s("Perfect Places", "Lorde", 2017),
  s("Solar Power", "Lorde", 2021),
  s("Stoned at the Nail Salon", "Lorde", 2021),
  s("Ho Hey", "The Lumineers", 2012),
  s("Stubborn Love", "The Lumineers", 2012),
  s("Cleopatra", "The Lumineers", 2016),
  s("Gloria", "The Lumineers", 2019),
  s("Sleep on the Floor", "The Lumineers", 2016),
  s("Budapest", "George Ezra", 2014),
  s("Barcelona", "George Ezra", 2018),
  s("Shotgun", "George Ezra", 2018),
  s("Hold My Girl", "George Ezra", 2018),
  s("Bloom", "The Paper Kites", 2010),
  s("Ribs", "Lorde", 2013),
  s("Mess Is Mine", "Vance Joy", 2013),
  s("Riptide", "Vance Joy", 2013),
  s("Georgia", "Vance Joy", 2013),
  s("Fire and the Flood", "Vance Joy", 2014),
  s("Take Your Time", "Sam Hunt", 2014),
  s("Something Like That", "Tim McGraw", 1999),
  s("Somebody's Heartbreak", "Hunter Hayes", 2012),
  s("Pumped Up Kicks", "Foster the People", 2010),
  s("Helena Beat", "Foster the People", 2011),
  s("Houdini", "Foster the People", 2014),
  s("Do I Wanna Know?", "Arctic Monkeys", 2013),
  s("R U Mine?", "Arctic Monkeys", 2013),
  s("Fluorescent Adolescent", "Arctic Monkeys", 2011),
  s("I Bet You Look Good on the Dancefloor", "Arctic Monkeys", 2005),
  s("505", "Arctic Monkeys", 2007),
  s("Crying Lightning", "Arctic Monkeys", 2009),
  s("Snap Out of It", "Arctic Monkeys", 2013),
  s("Why'd You Only Call Me When You're High?", "Arctic Monkeys", 2013),
  s("Four Out of Five", "Arctic Monkeys", 2018),
  s("Body Paint", "Arctic Monkeys", 2022),
  s("There'd Better Be a Mirrorball", "Arctic Monkeys", 2022),

  // ── Electronic / Dance ────────────────────────────────────────────────────
  s("Levels", "Avicii", 2011),
  s("Wake Me Up", "Avicii", 2013),
  s("Hey Brother", "Avicii", 2013),
  s("The Days", "Avicii", 2014),
  s("Addicted to You", "Avicii", 2013),
  s("Without You", "Avicii", 2013),
  s("Lay Me Down", "Avicii", 2013),
  s("You Make Me", "Avicii", 2013),
  s("Clarity", "Zedd", 2012),
  s("Stay the Night", "Zedd", 2013),
  s("Beautiful Now", "Zedd", 2015),
  s("The Middle", "Zedd", 2018),
  s("Stars Come Out", "Zedd", 2012),
  s("Spectrum", "Zedd", 2012),
  s("One More Time", "Daft Punk", 2000),
  s("Get Lucky", "Daft Punk", 2013),
  s("Around the World", "Daft Punk", 1997),
  s("Harder, Better, Faster, Stronger", "Daft Punk", 2001),
  s("Lose Yourself to Dance", "Daft Punk", 2013),
  s("Instant Crush", "Daft Punk", 2013),
  s("Within", "Daft Punk", 2013),
  s("Giorgio by Moroder", "Daft Punk", 2013),
  s("Alive", "Daft Punk", 2013),
  s("The Game of Love", "Daft Punk", 2003),
  s("Something About Us", "Daft Punk", 2001),
  s("Voyager", "Daft Punk", 2001),
  s("Superheroes", "The Script", 2014),
  s("Hall of Fame", "The Script", 2012),
  s("The Man Who Can't Be Moved", "The Script", 2008),
  s("Breakeven", "The Script", 2008),
  s("For the First Time", "The Script", 2010),
  s("Nothing", "The Script", 2008),
  s("Animals", "Martin Garrix", 2013),
  s("In the Name of Love", "Martin Garrix", 2016),
  s("Scared to Be Lonely", "Martin Garrix", 2017),
  s("Pizza", "Martin Garrix", 2014),
  s("Tremor", "Martin Garrix", 2014),
  s("Don't Look Down", "Martin Garrix", 2015),
  s("There for You", "Martin Garrix", 2016),
  s("Byte", "Martin Garrix", 2022),
  s("Turn Up the Speakers", "Martin Garrix", 2014),
  s("Forbidden Voices", "Martin Garrix", 2014),
  s("Titanium", "David Guetta", 2011),
  s("Without You", "David Guetta", 2011),
  s("She Wolf (Falling to Pieces)", "David Guetta", 2012),
  s("Play Hard", "David Guetta", 2012),
  s("Hey Mama", "David Guetta", 2015),
  s("2U", "David Guetta", 2017),
  s("Stay", "David Guetta", 2021),
  s("Summer Nights", "Tiësto", 2017),
  s("The Business", "Tiësto", 2020),
  s("10:35", "Tiësto", 2022),
  s("Lay Low", "Tiësto", 2022),
  s("Drive", "Tiësto", 2023),
  s("Pepas", "Farruko", 2021),
  s("Stay", "Kid LAROI", 2021),
  s("Without You", "Kid LAROI", 2020),
  s("Bloody Mary", "Lady Gaga", 2011),
  s("Judas", "Lady Gaga", 2011),
  s("The Edge of Glory", "Lady Gaga", 2011),
  s("Alejandro", "Lady Gaga", 2010),
  s("Paparazzi", "Lady Gaga", 2008),
  s("LoveGame", "Lady Gaga", 2008),

  // ── Latin ─────────────────────────────────────────────────────────────────
  s("Despacito", "Luis Fonsi", 2017),
  s("Bailando", "Enrique Iglesias", 2014),
  s("Hero", "Enrique Iglesias", 2001),
  s("Livin' la Vida Loca", "Ricky Martin", 1999),
  s("She Bangs", "Ricky Martin", 2000),
  s("La Copa de la Vida (The Cup of Life)", "Ricky Martin", 1998),
  s("Shakira: Bzrp Music Sessions, Vol. 53", "Bizarrap", 2023),
  s("Waka Waka (This Time for Africa)", "Shakira", 2010),
  s("Hips Don't Lie", "Shakira", 2005),
  s("Whenever, Wherever", "Shakira", 2001),
  s("She Wolf", "Shakira", 2009),
  s("Can't Remember to Forget You", "Shakira", 2014),
  s("Try Everything", "Shakira", 2016),
  s("La Tortura", "Shakira", 2005),
  s("Objection (Tango)", "Shakira", 2001),
  s("Monotonía", "Shakira", 2022),
  s("TQG", "Karol G", 2023),
  s("PROVENZA", "Karol G", 2022),
  s("MAÑANA SERÁ BONITO", "Karol G", 2023),
  s("QLONA", "Karol G", 2023),
  s("Tusa", "Karol G", 2019),
  s("Bichota", "Karol G", 2020),
  s("200 Copas", "Karol G", 2023),
  s("Mi Ex Tenía Razón", "Karol G", 2024),
  s("Contigo", "Karol G", 2024),
  s("GATÚBELA", "Karol G", 2022),
  s("Con Calma", "Daddy Yankee", 2019),
  s("Gasolina", "Daddy Yankee", 2004),
  s("Rompe", "Daddy Yankee", 2006),
  s("Shaky Shaky", "Daddy Yankee", 2016),
  s("El Farsante", "Ozuna", 2017),
  s("Taki Taki", "DJ Snake", 2018),
  s("Tusa", "Karol G", 2019),
  s("China", "Anuel AA", 2018),
  s("Me Porto Bonito", "Bad Bunny", 2022),
  s("Efecto", "Bad Bunny", 2022),
  s("Ojitos Lindos", "Bad Bunny", 2022),
  s("Un Verano Sin Ti", "Bad Bunny", 2022),
  s("Moscow Mule", "Bad Bunny", 2022),
  s("La Noche de Anoche", "Bad Bunny", 2020),
  s("Yo Perreo Sola", "Bad Bunny", 2020),
  s("MIA", "Bad Bunny", 2018),
  s("Callaíta", "Bad Bunny", 2019),
  s("DÁKITI", "Bad Bunny", 2020),
  s("Neverita", "Bad Bunny", 2022),
  s("Un Ratito", "Bad Bunny", 2022),
  s("Tití Me Preguntó", "Bad Bunny", 2022),
  s("Después de la Playa", "Bad Bunny", 2022),
  s("El Apagón", "Bad Bunny", 2022),
  s("Dos Mil 16", "Bad Bunny", 2023),
  s("Where She Goes", "Bad Bunny", 2023),
  s("Vou 3Xá", "Bad Bunny", 2024),
  s("LO QUE LE PASÓ A HAWAII", "Bad Bunny", 2024),
  s("NüEVA YöRK", "Bad Bunny", 2025),

  // ── K-Pop ─────────────────────────────────────────────────────────────────
  s("Dynamite", "BTS", 2020),
  s("Butter", "BTS", 2021),
  s("Permission to Dance", "BTS", 2021),
  s("DNA", "BTS", 2017),
  s("Boy With Luv", "BTS", 2019),
  s("Idol", "BTS", 2018),
  s("MIC Drop", "BTS", 2017),
  s("FAKE LOVE", "BTS", 2018),
  s("Black Swan", "BTS", 2020),
  s("ON", "BTS", 2020),
  s("Life Goes On", "BTS", 2020),
  s("Fly to My Room", "BTS", 2020),
  s("Stay", "BTS", 2021),
  s("Savage", "aespa", 2021),
  s("Next Level", "aespa", 2021),
  s("Black Mamba", "aespa", 2020),
  s("Dreams Come True", "aespa", 2021),
  s("Life's Too Short", "aespa", 2022),
  s("Girls", "aespa", 2022),
  s("Spicy", "aespa", 2023),
  s("Supernova", "aespa", 2024),
  s("Armageddon", "aespa", 2024),
  s("LOVE NOVA", "aespa", 2024),
  s("How Sweet", "NewJeans", 2024),
  s("Bubble Gum", "NewJeans", 2024),
  s("Super Shy", "NewJeans", 2023),
  s("ETA", "NewJeans", 2023),
  s("OMG", "NewJeans", 2023),
  s("Ditto", "NewJeans", 2022),
  s("Hype Boy", "NewJeans", 2022),
  s("Attention", "NewJeans", 2022),
  s("Hurt", "NewJeans", 2023),
  s("Right Now", "NewJeans", 2024),
  s("How Sweet", "NewJeans", 2024),
  s("Magnetic", "ILLIT", 2024),
  s("Lucky Girl Syndrome", "ILLIT", 2024),
  s("Midnight Guest", "fromis_9", 2022),
  s("Talk & Talk", "fromis_9", 2021),
  s("Love Me Like This", "NMIXX", 2023),
  s("O.O", "NMIXX", 2022),
  s("DICE", "NMIXX", 2022),
  s("Soñar (Loco)", "NMIXX", 2023),
  s("Love Countdown", "NMIXX", 2023),
  s("Dash", "NMIXX", 2024),
  s("Hard", "SHINee", 2023),
  s("Don't Call Me", "SHINee", 2021),
  s("Atlantis", "SHINee", 2021),
  s("View", "SHINee", 2015),
  s("Lucifer", "SHINee", 2010),
  s("Ring Ding Dong", "SHINee", 2009),
  s("Replay", "SHINee", 2008),
  s("Sherlock", "SHINee", 2012),
  s("Married to the Music", "SHINee", 2015),
  s("1 of 1", "SHINee", 2016),
  s("Tell Me What to Do", "SHINee", 2016),
  s("GOOD DAY", "IU", 2010),
  s("CELEBRITY", "IU", 2021),
  s("eight", "IU", 2020),
  s("Blueming", "IU", 2019),
  s("LILAC", "IU", 2021),
  s("Strawberry Moon", "IU", 2021),
  s("My Melody", "IU", 2022),
  s("Love wins all", "IU", 2024),
  s("Pink Venom", "BLACKPINK", 2022),
  s("Shut Down", "BLACKPINK", 2022),
  s("How You Like That", "BLACKPINK", 2020),
  s("Ice Cream", "BLACKPINK", 2020),
  s("Lovesick Girls", "BLACKPINK", 2020),
  s("Pretty Savage", "BLACKPINK", 2020),
  s("Kill This Love", "BLACKPINK", 2019),
  s("BOOMBAYAH", "BLACKPINK", 2016),
  s("DDU-DU DDU-DU", "BLACKPINK", 2018),
  s("As If It's Your Last", "BLACKPINK", 2017),
  s("Forever Young", "BLACKPINK", 2018),
  s("Stay", "BLACKPINK", 2016),
  s("Whistle", "BLACKPINK", 2016),
  s("The Girls", "BLACKPINK", 2022),
  s("Flower", "Jisoo", 2023),
  s("Queencard", "(G)I-DLE", 2023),
  s("Tomboy", "(G)I-DLE", 2022),
  s("LION", "(G)I-DLE", 2019),
  s("Oh My God", "(G)I-DLE", 2020),
  s("LATATA", "(G)I-DLE", 2018),
  s("HWAA", "(G)I-DLE", 2021),
  s("Nxde", "(G)I-DLE", 2022),
  s("I DO", "(G)I-DLE", 2023),
  s("Super Lady", "(G)I-DLE", 2024),
  s("MAMAME", "(G)I-DLE", 2024),
  s("STEREOTYPE", "STAYC", 2021),
  s("ASAP", "STAYC", 2021),
  s("BEAUTIFUL MONSTER", "STAYC", 2022),
  s("TEDDY BEAR", "STAYC", 2022),
  s("POPPY", "STAYC", 2023),
  s("Bubble", "STAYC", 2024),
  s("Eternal Sunshine", "EXID", 2019),
  s("UP & DOWN", "EXID", 2014),
  s("L.I.E", "EXID", 2016),
  s("Boy", "EXID", 2018),
  s("I Love You", "2NE1", 2012),
  s("FIRE", "2NE1", 2010),
  s("Can't Nobody", "2NE1", 2010),
  s("Come Back Home", "2NE1", 2014),
  s("Missing You", "2NE1", 2012),
  s("Lonely", "2NE1", 2011),
  s("Crush", "2NE1", 2014),
  s("GO AWAY", "2NE1", 2011),
  s("Clap", "SEVENTEEN", 2017),
  s("Pretty U", "SEVENTEEN", 2016),
  s("Don't Wanna Cry", "SEVENTEEN", 2017),
  s("Fear", "SEVENTEEN", 2019),
  s("ODE TO YOU", "SEVENTEEN", 2020),
  s("HOME;RUN", "SEVENTEEN", 2020),
  s("Rock with You", "SEVENTEEN", 2021),
  s("Ready to Love", "SEVENTEEN", 2021),
  s("DON'T WANNA CRY", "SEVENTEEN", 2017),
  s("Super", "SEVENTEEN", 2023),
  s("MAESTRO", "SEVENTEEN", 2024),
  s("Spill the Feels", "SEVENTEEN", 2024),
  s("God of Music", "SEVENTEEN", 2024),

  // ── 90s / 2000s Classics ─────────────────────────────────────────────────
  s("Baby One More Time", "Britney Spears", 1998),
  s("...Baby One More Time", "Britney Spears", 1998),
  s("Oops!... I Did It Again", "Britney Spears", 2000),
  s("Stronger", "Britney Spears", 2000),
  s("Slave 4 U", "Britney Spears", 2001),
  s("Everytime", "Britney Spears", 2004),
  s("Womanizer", "Britney Spears", 2008),
  s("3", "Britney Spears", 2009),
  s("Till the World Ends", "Britney Spears", 2011),
  s("Gimme More", "Britney Spears", 2007),
  s("Piece of Me", "Britney Spears", 2007),
  s("My Prerogative", "Britney Spears", 2004),
  s("Crazy", "Britney Spears", 1999),
  s("Sometimes", "Britney Spears", 1999),
  s("Bye Bye Bye", "*NSYNC", 2000),
  s("It's Gonna Be Me", "*NSYNC", 2000),
  s("Tearin' Up My Heart", "*NSYNC", 1997),
  s("I Want It That Way", "Backstreet Boys", 1999),
  s("Everybody (Backstreet's Back)", "Backstreet Boys", 1997),
  s("Larger Than Life", "Backstreet Boys", 1999),
  s("As Long as You Love Me", "Backstreet Boys", 1996),
  s("Quit Playing Games (with My Heart)", "Backstreet Boys", 1996),
  s("Show Me the Meaning of Being Lonely", "Backstreet Boys", 1999),
  s("What Makes You Beautiful", "One Direction", 2011),
  s("Story of My Life", "One Direction", 2013),
  s("Best Song Ever", "One Direction", 2013),
  s("That's What Makes You Beautiful", "One Direction", 2011),
  s("Live While We're Young", "One Direction", 2012),
  s("Drag Me Down", "One Direction", 2015),
  s("Night Changes", "One Direction", 2014),
  s("Truly Madly Deeply", "Savage Garden", 1997),
  s("I Knew I Loved You", "Savage Garden", 1999),
  s("Crash and Burn", "Savage Garden", 1999),
  s("Breathe (2 AM)", "Anna Nalick", 2005),
  s("Torn", "Natalie Imbruglia", 1997),
  s("Unwritten", "Natasha Bedingfield", 2004),
  s("These Words", "Natasha Bedingfield", 2004),
  s("Pocketful of Sunshine", "Natasha Bedingfield", 2008),
  s("Like a Prayer", "Madonna", 1989),
  s("Material Girl", "Madonna", 1984),
  s("Papa Don't Preach", "Madonna", 1986),
  s("Vogue", "Madonna", 1990),
  s("Ray of Light", "Madonna", 1998),
  s("Hung Up", "Madonna", 2005),
  s("4 Minutes", "Madonna", 2008),
  s("Living for Love", "Madonna", 2014),
  s("Beautiful Stranger", "Madonna", 1999),
  s("Holiday", "Madonna", 1983),

  // ── Afrobeats / Afropop ───────────────────────────────────────────────────
  s("Essence", "Wizkid", 2020),
  s("Come Closer", "Wizkid", 2017),
  s("Ojuelegba", "Wizkid", 2014),
  s("Fever", "Wizkid", 2019),
  s("Smile", "Wizkid", 2020),
  s("True Love", "Wizkid", 2022),
  s("Money & Love", "Wizkid", 2022),
  s("Kese (Dance)", "Wizkid", 2022),
  s("Water", "Tyla", 2023),
  s("Jump", "Tyla", 2023),
  s("ART", "Tyla", 2024),
  s("Butterflies", "Tyla", 2024),
  s("Truth or Dare", "Tyla", 2024),
  s("All Is Well", "Tyla", 2024),
  s("Jealousy", "Tyla", 2024),
  s("On and On", "Erykah Badu", 1997),
  s("Tyrant", "Tyla", 2024),
  s("Love You More", "Tyla", 2024),
  s("DIANA", "Tyla", 2024),
  s("Hypnotized", "Davido", 2021),
  s("Fall", "Davido", 2017),
  s("If", "Davido", 2017),
  s("Risky", "Davido", 2018),
  s("Fem", "Davido", 2020),
  s("Stand Strong", "Davido", 2022),
  s("Away", "Davido", 2022),
  s("Lagos", "Davido", 2019),
  s("Dami Duro", "Davido", 2011),
  s("Aye", "Davido", 2014),

  // ── Country ────────────────────────────────────────────────────────────────
  s("Jolene", "Dolly Parton", 1973),
  s("9 to 5", "Dolly Parton", 1980),
  s("I Will Always Love You", "Dolly Parton", 1973),
  s("Tennessee Whiskey", "Chris Stapleton", 2015),
  s("Traveller", "Chris Stapleton", 2015),
  s("Broken Halos", "Chris Stapleton", 2017),
  s("Starting Over", "Chris Stapleton", 2020),
  s("You Should Probably Leave", "Chris Stapleton", 2021),
  s("Whiskey and You", "Chris Stapleton", 2015),
  s("White Horse", "Chris Stapleton", 2023),
  s("Roses", "Outkast", 2003),
  s("Hey Ya!", "Outkast", 2003),
  s("The Way You Move", "Outkast", 2003),
  s("Ms. Jackson", "Outkast", 2000),
  s("ATLiens", "Outkast", 1996),
  s("BOB", "Outkast", 2000),
  s("Idlewild Blue (Don'tcha Worry 'Bout Me)", "Outkast", 2006),
  s("Morris Brown", "Outkast", 2006),

  // ── Jazz / Soul / Funk ────────────────────────────────────────────────────
  s("What a Wonderful World", "Louis Armstrong", 1967),
  s("La Vie en Rose", "Édith Piaf", 1947),
  s("Fly Me to the Moon", "Frank Sinatra", 1964),
  s("My Way", "Frank Sinatra", 1969),
  s("New York, New York", "Frank Sinatra", 1980),
  s("The Lady Is a Tramp", "Frank Sinatra", 1967),
  s("Killing Me Softly With His Song", "Roberta Flack", 1973),
  s("Feeling Good", "Nina Simone", 1965),
  s("I Put a Spell on You", "Nina Simone", 1965),
  s("Sinnerman", "Nina Simone", 1965),
  s("Strange Fruit", "Billie Holiday", 1939),
  s("God Bless the Child", "Billie Holiday", 1941),
  s("Superstition", "Stevie Wonder", 1972),
  s("Isn't She Lovely", "Stevie Wonder", 1976),
  s("Higher Ground", "Stevie Wonder", 1973),
  s("Signed, Sealed, Delivered I'm Yours", "Stevie Wonder", 1970),
  s("Sir Duke", "Stevie Wonder", 1976),
  s("I Just Called to Say I Love You", "Stevie Wonder", 1984),
  s("Part-Time Lover", "Stevie Wonder", 1985),
  s("Happy Birthday", "Stevie Wonder", 1980),
  s("I Wish", "Stevie Wonder", 1976),
  s("Boogie Wonderland", "Earth, Wind & Fire", 1979),
  s("September", "Earth, Wind & Fire", 1978),
  s("Let's Groove", "Earth, Wind & Fire", 1981),
  s("Shining Star", "Earth, Wind & Fire", 1975),
  s("Got to Get You into My Life", "Earth, Wind & Fire", 1975),
  s("Can't Hide Love", "Earth, Wind & Fire", 1976),
  s("After the Love Has Gone", "Earth, Wind & Fire", 1979),
  s("Fantasy", "Earth, Wind & Fire", 1978),
  s("That's the Way of the World", "Earth, Wind & Fire", 1975),
  s("Super Freak", "Rick James", 1981),
  s("Give It to Me Baby", "Rick James", 1981),
  s("Mary Jane", "Rick James", 1978),
  s("Ebony and Ivory", "Paul McCartney", 1982),
  s("My Girl", "The Temptations", 1964),
  s("Papa Was a Rollin' Stone", "The Temptations", 1972),
  s("Ball of Confusion", "The Temptations", 1970),
  s("I Heard It Through the Grapevine", "Marvin Gaye", 1968),
  s("Let's Get It On", "Marvin Gaye", 1973),
  s("Sexual Healing", "Marvin Gaye", 1982),
  s("What's Going On", "Marvin Gaye", 1971),
  s("Mercy Mercy Me (The Ecology)", "Marvin Gaye", 1971),
  s("Inner City Blues (Make Me Wanna Holler)", "Marvin Gaye", 1971),
  s("You Are Everything", "Marvin Gaye", 1974),
  s("Got to Give It Up", "Marvin Gaye", 1977),

  // ── The Beatles / Classic British ─────────────────────────────────────────
  s("Come Together", "The Beatles", 1969),
  s("Hey Jude", "The Beatles", 1968),
  s("Let It Be", "The Beatles", 1970),
  s("Yesterday", "The Beatles", 1965),
  s("Something", "The Beatles", 1969),
  s("Blackbird", "The Beatles", 1968),
  s("A Day in the Life", "The Beatles", 1967),
  s("Lucy in the Sky with Diamonds", "The Beatles", 1967),
  s("While My Guitar Gently Weeps", "The Beatles", 1968),
  s("In My Life", "The Beatles", 1965),
  s("Strawberry Fields Forever", "The Beatles", 1967),
  s("Penny Lane", "The Beatles", 1967),
  s("Twist and Shout", "The Beatles", 1963),
  s("I Am the Walrus", "The Beatles", 1967),
  s("Eleanor Rigby", "The Beatles", 1966),
  s("Norwegian Wood (This Bird Has Flown)", "The Beatles", 1965),
  s("Don't Let Me Down", "The Beatles", 1969),
  s("Lady Madonna", "The Beatles", 1968),
  s("Get Back", "The Beatles", 1969),
  s("Help!", "The Beatles", 1965),
  s("Ticket to Ride", "The Beatles", 1965),
  s("Revolution", "The Beatles", 1968),
  s("Imagine", "John Lennon", 1971),
  s("Working Class Hero", "John Lennon", 1970),
  s("Mind Games", "John Lennon", 1973),
  s("(Just Like) Starting Over", "John Lennon", 1980),
  s("Give Peace a Chance", "John Lennon", 1969),
  s("Jumpin' Jack Flash", "Rolling Stones", 1968),
  s("Paint It Black", "Rolling Stones", 1966),
  s("Wild Horses", "Rolling Stones", 1971),
  s("Gimme Shelter", "Rolling Stones", 1969),
  s("Start Me Up", "Rolling Stones", 1981),
  s("Satisfaction", "Rolling Stones", 1965),
  s("Sympathy for the Devil", "Rolling Stones", 1968),
  s("Angie", "Rolling Stones", 1973),
  s("Miss You", "Rolling Stones", 1978),
  s("Brown Sugar", "Rolling Stones", 1971),
  s("Let's Spend the Night Together", "Rolling Stones", 1967),
  s("Waiting for a Friend", "Rolling Stones", 1981),
  s("She's So Cold", "Rolling Stones", 1980),
  s("Emotional Rescue", "Rolling Stones", 1980),
  s("Under My Thumb", "Rolling Stones", 1966),
  s("As Tears Go By", "Rolling Stones", 1964),
  s("Space Oddity", "David Bowie", 1969),
  s("Heroes", "David Bowie", 1977),
  s("Ziggy Stardust", "David Bowie", 1972),
  s("Let's Dance", "David Bowie", 1983),
  s("Life on Mars?", "David Bowie", 1971),
  s("Changes", "David Bowie", 1971),
  s("Rebel Rebel", "David Bowie", 1974),
  s("Golden Years", "David Bowie", 1975),
  s("Fashion", "David Bowie", 1980),
  s("Starman", "David Bowie", 1972),
  s("Ashes to Ashes", "David Bowie", 1980),
  s("The Jean Genie", "David Bowie", 1972),
  s("Suffragette City", "David Bowie", 1972),
  s("Ziggy Stardust", "David Bowie", 1972),

  // ── Current / 2023-2026 ───────────────────────────────────────────────────
  s("Flowers", "Miley Cyrus", 2023),
  s("River", "Miley Cyrus", 2023),
  s("Angels Like You", "Miley Cyrus", 2020),
  s("Used to Be Young", "Miley Cyrus", 2023),
  s("Jaded", "Miley Cyrus", 2023),
  s("Is There Something I Should Know?", "Duran Duran", 1983),
  s("Cruel Summer", "Taylor Swift", 2019),
  s("Shake It Off", "Taylor Swift", 2014),
  s("Anti-Hero", "Taylor Swift", 2022),
  s("Mastermind", "Taylor Swift", 2022),
  s("Midnight Rain", "Taylor Swift", 2022),
  s("Bejeweled", "Taylor Swift", 2022),
  s("Snow on the Beach", "Taylor Swift", 2022),
  s("Question...?", "Taylor Swift", 2022),
  s("Hits Different", "Taylor Swift", 2022),
  s("Karma", "Taylor Swift", 2022),
  s("Sweet Nothing", "Taylor Swift", 2022),
  s("Marjorie", "Taylor Swift", 2020),
  s("Dear Reader", "Taylor Swift", 2022),
  s("Speak Now", "Taylor Swift", 2010),
  s("Back to December", "Taylor Swift", 2010),
  s("Mean", "Taylor Swift", 2011),
  s("The Story of Us", "Taylor Swift", 2011),
  s("Enchanted", "Taylor Swift", 2010),
  s("Treacherous", "Taylor Swift", 2012),
  s("All Too Well", "Taylor Swift", 2012),
  s("22", "Taylor Swift", 2012),
  s("I Almost Do", "Taylor Swift", 2012),
  s("We Are Never Ever Getting Back Together", "Taylor Swift", 2012),
  s("I Knew You Were Trouble", "Taylor Swift", 2012),
  s("Begin Again", "Taylor Swift", 2012),
  s("Out of the Woods", "Taylor Swift", 2014),
  s("Clean", "Taylor Swift", 2014),
  s("This Love", "Taylor Swift", 2014),
  s("How You Get the Girl", "Taylor Swift", 2014),
  s("New Romantics", "Taylor Swift", 2014),
  s("Getaway Car", "Taylor Swift", 2017),
  s("Gorgeous", "Taylor Swift", 2017),
  s("King of My Heart", "Taylor Swift", 2017),
  s("Dress", "Taylor Swift", 2017),
  s("Dancing with Our Hands Tied", "Taylor Swift", 2017),
  s("Cornelia Street", "Taylor Swift", 2019),
  s("The Man", "Taylor Swift", 2019),
  s("I Think He Knows", "Taylor Swift", 2019),
  s("Death By a Thousand Cuts", "Taylor Swift", 2019),
  s("Paper Rings", "Taylor Swift", 2019),
  s("exile", "Taylor Swift", 2020),
  s("Illicit Affairs", "Taylor Swift", 2020),
  s("This Is Me Trying", "Taylor Swift", 2020),
  s("Long Live", "Taylor Swift", 2010),
  s("The 1", "Taylor Swift", 2020),
  s("seven", "Taylor Swift", 2020),
  s("my tears ricochet", "Taylor Swift", 2020),
  s("peace", "Taylor Swift", 2020),
  s("hoax", "Taylor Swift", 2020),
  s("willow", "Taylor Swift", 2020),
  s("champagne problems", "Taylor Swift", 2020),
  s("gold rush", "Taylor Swift", 2020),
  s("'tis the damn season", "Taylor Swift", 2020),
  s("tolerate it", "Taylor Swift", 2020),
  s("no body no crime", "Taylor Swift", 2020),
  s("happiness", "Taylor Swift", 2020),
  s("dorothea", "Taylor Swift", 2020),
  s("coney island", "Taylor Swift", 2020),
  s("ivy", "Taylor Swift", 2020),
  s("cowboy like me", "Taylor Swift", 2020),
  s("long story short", "Taylor Swift", 2020),
  s("Speak Now (Taylor's Version)", "Taylor Swift", 2023),
  s("Eyes Open", "Taylor Swift", 2012),
  s("Safe & Sound", "Taylor Swift", 2011),
  s("Both of Us", "Taylor Swift", 2012),
  s("Highway Don't Care", "Taylor Swift", 2013),
  s("Highway Don't Care", "Tim McGraw", 2013),
  s("I'm Only Me When I'm with You", "Taylor Swift", 2006),
  s("A Place in This World", "Taylor Swift", 2006),
  s("Picture to Burn", "Taylor Swift", 2006),
  s("Teardrops on My Guitar", "Taylor Swift", 2006),
  s("Our Song", "Taylor Swift", 2006),
  s("Cold Hard Truth", "Taylor Swift", 2006),
  s("The Outside", "Taylor Swift", 2006),
  s("Change", "Taylor Swift", 2007),
  s("Jump Then Fall", "Taylor Swift", 2009),
  s("Untouchable", "Taylor Swift", 2009),
  s("Forever & Always", "Taylor Swift", 2008),
  s("The Other Side of the Door", "Taylor Swift", 2009),
  s("White Horse", "Taylor Swift", 2008),
  s("You're Not Sorry", "Taylor Swift", 2008),
  s("The Way I Loved You", "Taylor Swift", 2008),
  s("Come In with the Rain", "Taylor Swift", 2009),
  s("Breathe", "Taylor Swift", 2008),
  s("Tell Me Why", "Taylor Swift", 2008),
  s("Last Kiss", "Taylor Swift", 2010),
  s("Innocent", "Taylor Swift", 2010),
  s("Superman", "Taylor Swift", 2010),
  s("Ours", "Taylor Swift", 2010),
  s("If This Was a Movie", "Taylor Swift", 2010),
  s("Everything Has Changed", "Taylor Swift", 2012),
  s("Come Back...Be Here", "Taylor Swift", 2012),
  s("Girl at Home", "Taylor Swift", 2012),
  s("Sad Beautiful Tragic", "Taylor Swift", 2012),
  s("Holy Ground", "Taylor Swift", 2012),
  s("Stay Stay Stay", "Taylor Swift", 2012),
  s("Red", "Taylor Swift", 2012),
  s("State of Grace", "Taylor Swift", 2012),
  s("Starlight", "Taylor Swift", 2012),
  s("The Lucky One", "Taylor Swift", 2012),
  s("Welcome to New York", "Taylor Swift", 2014),
  s("I Wish You Would", "Taylor Swift", 2014),
  s("Wildest Dreams", "Taylor Swift", 2015),
  s("You Are in Love", "Taylor Swift", 2014),
  s("New Romantics", "Taylor Swift", 2014),
  s("Strange Clouds", "B.o.B", 2012),
  s("Airplanes", "B.o.B", 2010),
  s("Nothin' on You", "B.o.B", 2010),
  s("Beautiful Girls", "Sean Kingston", 2007),
  s("One More Night", "Maroon 5", 2012),
  s("Moves Like Jagger", "Maroon 5", 2011),
  s("Sugar", "Maroon 5", 2014),
  s("Girls Like You", "Maroon 5", 2017),
  s("Animals", "Maroon 5", 2014),
  s("Payphone", "Maroon 5", 2012),
  s("Memories", "Maroon 5", 2019),
  s("Sunday Morning", "Maroon 5", 2002),
  s("This Love", "Maroon 5", 2002),
  s("She Will Be Loved", "Maroon 5", 2004),
  s("Harder to Breathe", "Maroon 5", 2002),
  s("Wake Up Call", "Maroon 5", 2007),
  s("Makes Me Wonder", "Maroon 5", 2007),
  s("Won't Go Home Without You", "Maroon 5", 2007),
  s("If I Never See Your Face Again", "Maroon 5", 2008),
  s("Misery", "Maroon 5", 2010),
  s("Daylight", "Maroon 5", 2012),
  s("Lucky Strike", "Maroon 5", 2012),
  s("Feelings", "Maroon 5", 2018),
  s("What Lovers Do", "Maroon 5", 2017),
  s("Cold", "Maroon 5", 2017),
  s("Wait", "Maroon 5", 2018),
  s("Maps", "Maroon 5", 2014),
  s("Stutter", "Maroon 5", 2012),
  s("Nothing Lasts Forever", "Maroon 5", 2012),
  s("Give a Little More", "Maroon 5", 2010),
  s("Tangled", "Maroon 5", 2010),
  s("Never Gonna Leave This Bed", "Maroon 5", 2010),

  // ── Hyperpop / Future Bass ────────────────────────────────────────────────
  s("good 4 u", "Olivia Rodrigo", 2021),
  s("drivers license", "Olivia Rodrigo", 2021),
  s("brutal", "Olivia Rodrigo", 2021),
  s("traitor", "Olivia Rodrigo", 2021),
  s("favorite crime", "Olivia Rodrigo", 2021),
  s("happier", "Olivia Rodrigo", 2021),
  s("deja vu", "Olivia Rodrigo", 2021),
  s("hope ur ok", "Olivia Rodrigo", 2021),
  s("vampire", "Olivia Rodrigo", 2023),
  s("bad idea right?", "Olivia Rodrigo", 2023),
  s("get him back!", "Olivia Rodrigo", 2023),
  s("lacy", "Olivia Rodrigo", 2023),
  s("ballad of a homeschooled girl", "Olivia Rodrigo", 2023),
  s("making the bed", "Olivia Rodrigo", 2023),
  s("logical", "Olivia Rodrigo", 2023),
  s("all-american bitch", "Olivia Rodrigo", 2023),
  s("teenage dream", "Olivia Rodrigo", 2023),
  s("pretty isn't pretty", "Olivia Rodrigo", 2023),
  s("the grudge", "Olivia Rodrigo", 2023),
  s("love is embarrassing", "Olivia Rodrigo", 2023),
  s("1 step forward, 3 steps back", "Olivia Rodrigo", 2021),
  s("brutal", "Olivia Rodrigo", 2021),
];
